export const SUBJECTS = [
  "Mathematics",
  "Algebra",
  "Calculus",
  "Geometry",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Programming",
  "Web Development",
  "Data Science",
  "English",
  "Literature",
  "Writing",
  "Spanish",
  "French",
  "German",
  "History",
  "Geography",
  "Economics",
  "Business",
  "Accounting",
  "Psychology",
  "Philosophy",
  "Music",
  "Art",
  "Engineering",
  "Medicine",
  "Law",
] as const;

export type Subject = typeof SUBJECTS[number];
